PROJECT/src/java/model/Cart.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author doson
 */
public class Cart {
    private List<Item> items;

    public Cart() {
        items = new ArrayList<>();
    }

    public Cart(List<Item> items) {
        this.items = items;
    }

    public List<Item> getItems() {
        return items;
    }

    public void setItems(List<Item> items) {
        this.items = items;
    }
    
    public int getQuantityById(int id){
        return getItemById(id).getQuantity();
    }
    
    private Item getItemById(int id){
        for(Item i:items){
            if(i.getProduct().getIdProduct()==id){
                return i;
            }
        }
        return null;
    }
    
    public void addItem(Item t){
        if(getItemById(t.getProduct().getIdProduct())!=null){
            Item m = getItemById(t.getProduct().getIdProduct());
            m.setQuantity(m.getQuantity()+t.getQuantity());
        }
        else{
            items.add(t);
        }
    }
    public void removeItem(int id){
        if(getItemById(id)!=null){
            items.remove(getItemById(id));
        }
    }
    
    public double getTotalMoney(){
        double t = 0;
        for(Item i:items){
            t+= i.getQuantity() * i.getPrice();
        }
        return t;
    }
    private Product getProductById(int id, List<Product> list){
        for(Product i:list){
            if(i.getIdProduct()==id){
                return i;
            }
        }
        return null;
    }
    public Cart(String txt,List<Product> list){
        items = new ArrayList<>();
        try {
            if(txt != null && txt.length()!=0){
            String [] s = txt.split(",");
            for(String i:s){
                String [] n = i.split(":");
                int id = Integer.parseInt(n[0]);
                int quantity = Integer.parseInt(n[1]);
                Product p = getProductById(id, list);
                Item t = new Item(p, quantity, p.getPrice());
                addItem(t);
            }
        }
        } catch (Exception e) {
        }
    }
}

PROJECT/src/java/model/OrderDetail.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

/**
 *
 * @author doson
 */
public class OrderDetail {
    private int oid,quantity;
    private Product product;
    private double price;
    public OrderDetail() {
    }

    public OrderDetail(int oid, int quantity, Product product, double price) {
        this.oid = oid;
        this.quantity = quantity;
        this.product = product;
        this.price = price;
    }
    public int getOid() {
        return oid;
    }

    public void setOid(int oid) {
        this.oid = oid;
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }



    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }
    
}

PROJECT/src/java/cotroller/ChangePasswordServlet.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cotroller;

import dal.CustomerDAO;
import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import model.Customer;

/**
 *
 * @author doson
 */
public class ChangePasswordServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet ChangePasswordServlet</title>");
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet ChangePasswordServlet at " + request.getContextPath() + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        request.setCharacterEncoding("utf-8");
        response.sendRedirect("changepassword.jsp");
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        request.setCharacterEncoding("utf-8");
        HttpSession session = request.getSession();
        Customer c = (Customer) session.getAttribute("account");
        CustomerDAO cd = new CustomerDAO();
        String oldpass = request.getParameter("oldpass");
        String newpass = request.getParameter("newpass");
        String newpassag = request.getParameter("newpassag");
        if (c != null) {
            if (c.getPassWord().equals(oldpass) && newpass.matches("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,}$") && newpass.equals(newpassag) && !newpass.equals(oldpass)) {
                cd.changePass(new Customer(c.getUserName(), newpass, c.getNameCustomer(), c.getDOB(), c.getAddress(), c.getPhone(), c.getAdmin()));
                session.invalidate();
                request.getRequestDispatcher("login.jsp").forward(request, response);
            } else {
                request.setAttribute("errchange", "Đổi mật khẩu không thành công");
                request.getRequestDispatcher("changepassword.jsp").forward(request, response);
            }
        }
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

PROJECT/src/java/cotroller/ChangeShipperServlet.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cotroller;

import dal.CustomerDAO;
import dal.ShipperDAO;
import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import model.Customer;
import model.Shipper;

/**
 *
 * @author doson
 */
public class ChangeShipperServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet ChangeShipperServlet</title>");            
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet ChangeShipperServlet at " + request.getContextPath() + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        request.setCharacterEncoding("utf-8");
        response.sendRedirect("changeshipper.jsp");
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        request.setCharacterEncoding("utf-8");
        HttpSession session = request.getSession();
        Shipper c = (Shipper) session.getAttribute("accountshipper");
        ShipperDAO sd = new ShipperDAO();
        String oldpass = request.getParameter("oldpass");
        String newpass = request.getParameter("newpass");
        String newpassag = request.getParameter("newpassag");
        if (c != null) {
            if (c.getPasswordShipper().equals(oldpass) && newpass.matches("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,}$") && newpass.equals(newpassag) && !newpass.equals(oldpass)) {
                sd.changepasswordShipper(new Shipper(c.getUserNameShipper(), newpass, c.getFullName(), c.getDob(), c.getAddress(), c.getPhone()));
                session.invalidate();
                request.getRequestDispatcher("loginshipper.jsp").forward(request, response);
            } else {
                request.setAttribute("errchange", "Đổi mật khẩu không thành công");
                request.getRequestDispatcher("changeshipper.jsp").forward(request, response);
            }
        }
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

PROJECT/src/java/cotroller/CheckOutServlet.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cotroller;

import dal.OderDAO;
import dal.ProductDAO;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;
import javax.servlet.ServletException;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import model.Cart;
import model.Customer;
import model.Product;

/**
 *
 * @author doson
 */
public class CheckOutServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet CheckOutServlet</title>");            
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet CheckOutServlet at " + request.getContextPath() + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        ProductDAO pd = new ProductDAO();
        List<Product> list1 = pd.getAllProduct();
        Cookie [] arr = request.getCookies();
        String txt = "";
        if(arr!=null){
            for(Cookie o:arr){
                if(o.getName().equals("cart")){
                    txt+=o.getValue();
                }
            }
        }
        Cart cart = new Cart(txt, list1);
        request.setAttribute("cart", cart);
        request.getRequestDispatcher("checkout.jsp").forward(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String name = request.getParameter("deliveryname");
        String address = request.getParameter("deliveryaddress");
        String phone = request.getParameter("deliveryphone");
        ProductDAO pd = new ProductDAO();
        List<Product> list1 = pd.getAllProduct();
        Cookie [] arr = request.getCookies();
        String txt = "";
        if(arr!=null){
            for(Cookie o:arr){
                if(o.getName().equals("cart")){
                    txt+=o.getValue();
                }
            }
        }
        Cart cart = new Cart(txt, list1);
        HttpSession session = request.getSession();
        Customer a = (Customer)session.getAttribute("account");
        if(a==null){
            response.sendRedirect("login.jsp");
        }
        else{
            OderDAO od = new OderDAO();
            od.addOrder(a, cart,name, address, phone);
            Cookie c = new Cookie("cart", "");
            c.setMaxAge(0);
            response.addCookie(c);
            request.getRequestDispatcher("list").forward(request, response);
        }
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

PROJECT/web/changepassword.jsp
<%-- 
    Document   : changepassword
    Created on : Mar 8, 2022, 10:42:33 PM
    Author     : doson
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Đổi mật khẩu</title>
        <link href="css/login/login.css" rel="stylesheet">
    <body>
        <section class="container">
            <div class="login">
                <h1>Đổi mật khẩu</h1>
                <p style="color: red">${requestScope.errchange}</p>
                <form method="post" action="changepass">
                    <p><input type="password" name="oldpass" value="" placeholder="Mật khẩu cũ"></p>
                    <p><input type="password" name="newpass" value="" placeholder="Mật khẩu mới"></p>
                    <p><input type="password" name="newpassag" value="" placeholder="Nhập lại mật khẩu mới"></p>
                    <p class="submit"><input type="submit" value="Đổi mật khẩu"></p>
                </form>
            </div>
        </section>
    </body>
</html>

PROJECT/web/changeshipper.jsp
<%-- 
    Document   : changeshipper
    Created on : Mar 13, 2022, 11:51:05 PM
    Author     : doson
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Đổi mật khẩu Shipper</title>
        <link href="css/login/login.css" rel="stylesheet">
    <body>
        <section class="container">
            <div class="login">
                <h1>Đổi mật khẩu Shipper</h1>
                <p style="color: red">${requestScope.errchange}</p>
                <form method="post" action="changeshipper">
                    <p><input type="password" name="oldpass" value="" placeholder="Mật khẩu cũ"></p>
                    <p><input type="password" name="newpass" value="" placeholder="Mật khẩu mới"></p>
                    <p><input type="password" name="newpassag" value="" placeholder="Nhập lại mật khẩu mới"></p>
                    <p class="submit"><input type="submit" value="Đổi mật khẩu"></p>
                </form>
            </div>
        </section>
    </body>
</html>

PROJECT/web/listorderbycustomer.jsp
<%-- 
    Document   : order
    Created on : Mar 12, 2022, 5:19:23 PM
    Author     : doson
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html lang="zxx">
    <head>
        <meta charset="UTF-8">
        <meta name="description" content="Ogani Template">
        <meta name="keywords" content="Ogani, unica, creative, html">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Ogani | Template</title>

        <!-- Google Font -->
        <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

        <!-- Css Styles -->
        <link rel="stylesheet" href="css/bootstrap.css" type="text/css">
        <link rel="stylesheet" href="css/font-awesome.min.css" type="text/css">
        <link rel="stylesheet" href="css/elegant-icons.css" type="text/css">
        <link rel="stylesheet" href="css/nice-select.css" type="text/css">
        <link rel="stylesheet" href="css/jquery-ui.min.css" type="text/css">
        <link rel="stylesheet" href="css/owl.carousel.min.css" type="text/css">
        <link rel="stylesheet" href="css/slicknav.min.css" type="text/css">
        <link rel="stylesheet" href="css/style.css" type="text/css">
    </head>
    <body>
        <header class="header">
            <div class="header__top">
                <div class="container">
                    <c:set var="acc" value="${sessionScope.account}"/>
                    <c:if test="${acc.userName==null}">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="header__top__left">
                                    <ul>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="header__top__right">
                                    <div class="header__top__right__social">
                                        <a href="#"><i class="fa fa-facebook"></i></a>
                                        <a href="#"><i class="fa fa-linkedin"></i></a>
                                    </div>
                                    <div class="header__top__right__auth">
                                        <a href="login.jsp"><i class="fa fa-user"></i> Đăng nhập</a>
                                        <a href="register.jsp">Đăng ký</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </c:if>
                    <c:if test="${acc.userName!=null}">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="header__top__left">
                                    <ul>
                                        <li><i class="fa fa-envelope"></i><a href="profile.jsp">Xin chào ${acc.nameCustomer}</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="header__top__right">
                                    <div class="header__top__right__social">
                                        <a href="#"><i class="fa fa-facebook"></i></a>
                                        <a href="#"><i class="fa fa-linkedin"></i></a>
                                    </div>
                                    <div class="header__top__right__auth">
                                        <a href="logout"><i class="fa fa-user"></i>Đăng xuất</a>
                                        <a href="changepass">Đổi mật khẩu</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </c:if>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="header__logo">
                            <a href="list"><img src="image/logo.png" alt="" width="100px" height="100px"></a>
                        </div>
                    </div>
                    <div class="col-lg-9">
                        <div class="hero__search">
                            <div class="hero__search__form">
                                <form action="search">
                                    <div class="hero__search__categories">
                                        Tất cả sản phẩm
                                    </div>
                                    <input type="text" placeholder="Tìm kiếm" name="key">
                                    <button type="submit" class="site-btn">Tìm kiếm</button>
                                </form>
                            </div>
                            <c:if test="${acc.admin eq 'admin'}">
                                &nbsp;&nbsp;&nbsp;&nbsp; <button><a href="check?action=add">Thêm sảm phẩm</a></button>
                                <button><a href="order">Đơn đặt hàng</a></button>
                            </c:if>
                            <c:if test="${acc.userName!=null}" >    
                                &nbsp;&nbsp;&nbsp;&nbsp; <img src="image/images.png" width="50px" height="50px">
                                <a href="show">Giỏ hàng</a>
                            </c:if>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <section class="shoping-cart spad">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="shoping__cart__table">
                            <table border="1px">
                                <thead>
                                    <tr>
                                        <th>Tên khách hàng</th>
                                        <th>Ngày đặt</th>
                                        <th>Địa chỉ nhận</th>
                                        <th>Số điện thoại</th>
                                        <th>Tổng tiền</th>
                                        <th>Tình trạng giao hàng</th>
                                        <th>Xem thêm</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <c:set var="o" value="${requestScope.cart}"/>
                                    <c:forEach var="o" items="${requestScope.listO}">
                                        <tr>
                                            <td class="shoping__cart__price">
                                                ${o.nameCustomer}
                                            </td>
                                            <td class="shoping__cart__price">
                                                ${o.dateCreate}
                                            </td>
                                            <td class="shoping__cart__price">
                                                ${o.deliveryAddress}
                                            </td>
                                            <td class="shoping__cart__price">
                                                ${o.deliveryPhone}
                                            </td>
                                            <td class="shoping__cart__price">
                                                ${o.totalMoney}
                                            </td>
                                            <td class="shoping__cart__price">
                                                ${(o.done eq 'Yes')?"Đã giao":"Chưa giao"}
                                            </td>
                                            <td class="shoping__cart__price">
                                                <button><a href="orderdetail?id=${o.idOder}">Chi tiết đơn hàng</a></button>
                                            </td>
                                        </tr>
                                    </c:forEach>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="shoping__cart__btns">
                            <a href="list" class="primary-btn cart-btn">Quay về trang trủ</a>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="shoping__continue">
                            <div class="shoping__discount">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </body>
</html>

PROJECT/web/loginshipper.jsp
<%-- 
    Document   : login
    Created on : Feb 20, 2022, 4:54:20 PM
    Author     : doson
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Đăng nhập</title>
        <link href="css/login/login.css" rel="stylesheet">
    <body>
        <section class="container">
            <div class="login">
                <h1>Đăng nhập vào Shipper</h1>
                <p style="color: red">${requestScope.error}</p>
                <form method="get" action="loginshipper">
                    <p><input type="text" name="user" value="${cookie.users.value}" placeholder="Tài khoản"></p>
                    <p><input type="password" name="pass" value="${cookie.passs.value}" placeholder="Mật khẩu"></p>
                    <p class="remember_me">
                        <label>
                            <input type="checkbox" ${(cookie.rems.value eq 'ON')?"checked":""} name="rem" id="remember_me" value="ON">
                            Nhớ mật khẩu
                        </label>
                    </p>
                    <p class="submit"><input type="submit" value="Đăng nhập"></p>
                </form>
            </div>

            <div class="login-help">
                <p>Bạn chưa có tài khoản? <a href="register.jsp">Hãy đăng ký</a>.</p>
                <p><a href="login.jsp">Quay lại trang đăng nhập của khách hảng</a></p>
            </div>
        </section>
    </body>
</html>

PROJECT/web/register.jsp
<%-- 
    Document   : register
    Created on : Feb 20, 2022, 5:30:06 PM
    Author     : doson
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <link href="css/login/login.css" rel="stylesheet">
    </head>
    <body>
        <section class="container">
            <div class="login">
        <h1>Tạo tài khoản mới</h1>
        <form action="register">
            <p style="color: red">${requestScope.errorUser}<input type="text" name="userc" value="" placeholder="Nhập tên đăng nhập"></p>
            <p style="color: red">${requestScope.errorPass}<input type="password" name="passc" placeholder="Nhập mật khẩu"></p>
            <p style="color: red"><input type="password" name="passoldc" placeholder="Nhập lại mật khẩu">${requestScope.errorPassAgain}</p>
            <input type="text" name="namec" placeholder="Họ và tên">
            <input type="date" name="dobc" placeholder="Enter Date Of Birth">
            <input type="text" name="addressc" placeholder="Địa chỉ">
            <p style="color: red"><input type="text" name="phonec" placeholder="Số điện thoại">${requestScope.errorPhone}</p>
            <input type="text" name="admin" placeholder="Nhập mã để trở thành admin">
            <input type="submit" value="Đăng ký">
        </form>
            </div>
        </section>
    </body>
</html>